name: docs-build-static-action
description: Build HTML documentation

inputs:
  src-root:
    default: "./"
  build-root:
    default: "./_site"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm i @diplodoc/cli -g
      shell: bash

    - name: Build HTML
      id: build-html
      run: |
        set +e
        set -o pipefail

        yfm -i ${{ inputs.src-root }} -o ${{ inputs.build-root }} | tee './build-html.log'

        echo "exitcode=$?" >> $GITHUB_OUTPUT
      shell: bash

    - name: Upload HTML build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: static-html-output
        path: ${{ inputs.build-root }}
        retention-days: 1

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: static-build-log-html
        path: ./build-html.log
        retention-days: 1

    - name: Exit
      run: |
        exitcode=${{ steps.build-html.outputs.exitcode }}

        if [ "$exitcode" -eq 0 ]; then
            echo "Build exited successfully."
        else
          echo "Build exited with an error. Exit code: $exitcode"
          exit $exitcode
        fi
      shell: bash
